name: YOLO Commit

on:
  workflow_dispatch:

jobs:
  yolo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Tambahkan file YOLO dan commit
        run: |
          echo "YOLO dari GitHub Actions" >> yolo.txt
          git add yolo.txt
          git commit -m "YOLO commit dari Actions"
          git push origin HEAD:main
